name: VPS
on: workflow_dispatch

jobs:
  my-vps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # الحل للمشكل: نتيليشارجيوه ونتبتوه يدوياً بطريقة مضمونة
      - name: Install Tailscale Manually
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-runner-vps --ssh

      - name: Set Password for Runner
        run: echo "runner:123456" | sudo chpasswd

      - name: Wait for connection
        run: |
          echo "✅ Tailscale is UP! Check your dashboard."
          echo "IP Address:"
          tailscale ip -4
          echo "⏳ Session will be alive for 6 hours..."
          sleep 6h
